### ISSUE TITLE
您好，brook启动失败应为brook更改了配置的参数。

### ISSUE THREAD

**Issue by echoowall** [ECIAP/brook#1]
Run brook relay
$ brook relay -f :9999 -t 1.2.3.4:9999
Assume your relay server IP is 5.6.7.8, then send request to 5.6.7.8:9999 is equal with send request to 1.2.3.4:9999 now

More parameters: $ brook relay -h
请修复，谢谢！

**Comment by 110560** [comment]
文件/etc/init.d/brook-pf

servers_all="${servers_all}-l ":${user_port} ${user_ip_pf}:${user_port_pf}" "

的 -l 改成 --fromto 就可以了 
v20200801以上的brook版本需要这样 作者改改谢谢。。。。

https://www.hostloc.com/thread-804541-1-1.html

**Comment by 110560** [comment]
详细的看网址里面解释的 

麻烦作者修改下代码

**Comment by SXR666** [comment]
> Run brook relay
> $ brook relay -f :9999 -t 1.2.3.4:9999
> Assume your relay server IP is 5.6.7.8, then send request to 5.6.7.8:9999 is equal with send request to 1.2.3.4:9999 now
> 
> More parameters: $ brook relay -h
> 请修复，谢谢！

https://github.com/SXR666/brook-pf
请尝试此分支

**Comment by ECIAP** [comment]
> 详细的看网址里面解释的
> 
> 麻烦作者修改下代码

感谢提供方案，已经改好啦

**Comment by ECIAP** [comment]
> Run brook relay
> $ brook relay -f :9999 -t 1.2.3.4:9999
> Assume your relay server IP is 5.6.7.8, then send request to 5.6.7.8:9999 is equal with send request to 1.2.3.4:9999 now
> 
> More parameters: $ brook relay -h
> 请修复，谢谢！

此问题已被修复
