### ISSUE TITLE
vps系统重装了 一样的问题。。。

### ISSUE THREAD

**Issue by 110560** [ECIAP/brook#2]
USAGE:
   brook relays [command options] [arguments...]

OPTIONS:
   --fromto value      Listen address and relay to address, like '0.0.0.0:1080 1.2.3.4:1080'
   --tcpTimeout value  connection deadline time (s) (default: 0)
   --udpTimeout value  connection deadline time (s) (default: 60)
   --help, -h          show help (default: false)

**Comment by ECIAP** [comment]
系统环境多少，我在Centos 7.6 试了一下没问题

**Comment by 110560** [comment]
debian 10 
用的 sudo apt-get install dnsutils -y && sudo apt-get install wget -y && wget https://raw.githubusercontent.com/ECIAP/brook/master/brook-pf-mod.sh && chmod +x brook-pf-mod.sh && bash brook-pf-mod.sh

**Comment by 110560** [comment]
是的

**Comment by 110560** [comment]
[信息] 检测到 Brook 最新版本为 [ v20210401 ]
[信息] 当前 Brook 已是最新版本 [ v20210401 ]

**Comment by 110560** [comment]
脚本已更新为最新版本[ 1.0.0 ] !(注意：因为更新方式为直接覆盖当前运行的脚本，所以可 能下面会提示一些报错，无视即可

**Comment by ECIAP** [comment]
> 是的

这不应该，我在Vultr上开了一台debian10可以成功运行

**Comment by 110560** [comment]
debian 9
root@vultr:~# date
Sun Jun  6 13:11:29 CST 2021

USAGE:
   brook relays [command options] [arguments...]

OPTIONS:
   --fromto value      Listen address and relay to address, like '0.0.0.0:9999 1.2.3.4:9999'
   --tcpTimeout value  connection deadline time (s) (default: 0)
   --udpTimeout value  connection deadline time (s) (default: 60)
   --help, -h          show help (default: false)

**Comment by 110560** [comment]
debian10 也试了。。 
这个对吧，
brook默认下载的最新的
wget https://raw.githubusercontent.com/ECIAP/brook/master/brook-pf-mod.sh && chmod +x brook-pf-mod.sh && bash brook-pf-mod.sh

**Comment by ECIAP** [comment]
> debian10 也试了。。
> 这个对吧，
> brook默认下载的最新的
> wget https://raw.githubusercontent.com/ECIAP/brook/master/brook-pf-mod.sh && chmod +x brook-pf-mod.sh && bash brook-pf-mod.sh

对的，请执行此命令以及 apt-get install dnsutils -y

**Comment by ECIAP** [comment]
> debian10 也试了。。
> 这个对吧，
> brook默认下载的最新的
> wget https://raw.githubusercontent.com/ECIAP/brook/master/brook-pf-mod.sh && chmod +x brook-pf-mod.sh && bash brook-pf-mod.sh

另外在执行之前请 rm brook-pf-mod.sh
