### ISSUE TITLE
[错误] Brook-pf 启动失败 !

### ISSUE THREAD

**Issue by AndersonGhost** [ECIAP/brook#4]
不知何故，有时候 Brook-pf 总是启动失败 !

**Comment by ECIAP** [comment]
请给出错误日志

**Comment by AndersonGhost** [comment]
您没有出现过Brook-pf 启动失败的情形吗？每次都成功了吗？

当添加两个以上的服务器时，显示启动失败，但实际上是可以中转的。

只添加一个服务器，有时候会成功，有时候会失败。

**Comment by ECIAP** [comment]
> 您没有出现过Brook-pf 启动失败的情形吗？每次都成功了吗？
> 
> 当添加两个以上的服务器时，显示启动失败，但实际上是可以中转的。
> 
> 只添加一个服务器，有时候会成功，有时候会失败。

很抱歉，我无法复现此错误

**Comment by ECIAP** [comment]
> 您没有出现过Brook-pf 启动失败的情形吗？每次都成功了吗？
> 
> 当添加两个以上的服务器时，显示启动失败，但实际上是可以中转的。
> 
> 只添加一个服务器，有时候会成功，有时候会失败。

我需要更多的信息以检查
你至少需要提供以下信息
 - 错误日志
 - 系统环境
